// find_dups.go
package main

import (
	"crypto/sha256"
	"encoding/csv"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"sync"
	"syscall"
	"time"
)

type FileInfo struct {
	ID      int
	Path    string
	Size    int64
	ModTime time.Time
	Birth   time.Time
	Hash    string
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Использование: find_dups <директория1> [<директория2> ...]")
		os.Exit(1)
	}
	roots := os.Args[1:]

	startTotal := time.Now()

	// ----- 1. Сбор обычных файлов (без симлинков) -----
	var allFiles []FileInfo
	var scanned int
	var nextID = 1
	var mu sync.Mutex

	for _, root := range roots {
		err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return nil // игнорируем ошибки доступа
			}
			if d.IsDir() {
				return nil
			}
			info, err := d.Info()
			if err != nil {
				return nil
			}
			// Проверяем обычный файл (не symlink, не device)
			if !info.Mode().IsRegular() {
				return nil
			}
			mu.Lock()
			defer mu.Unlock()
			scanned++
			size := info.Size()
			modTime := info.ModTime()
			var birthTime time.Time
			if stat, ok := info.Sys().(*syscall.Stat_t); ok {
				birthTime = time.Unix(stat.Birthtimespec.Sec, stat.Birthtimespec.Nsec)
			} else {
				birthTime = modTime
			}
			allFiles = append(allFiles, FileInfo{
				ID:      nextID,
				Path:    path,
				Size:    size,
				ModTime: modTime,
				Birth:   birthTime,
			})
			nextID++
			return nil
		})
		if err != nil {
			fmt.Fprintf(os.Stderr, "Ошибка обхода %s: %v\n", root, err)
		}
	}

	// ----- 2. Группировка по размеру -----
	bySize := make(map[int64][]*FileInfo)
	for i := range allFiles {
		bySize[allFiles[i].Size] = append(bySize[allFiles[i].Size], &allFiles[i])
	}

	// ----- 3. Параллельное хеширование -----
	var filesToHash []*FileInfo
	for _, files := range bySize {
		if len(files) > 1 {
			filesToHash = append(filesToHash, files...)
		}
	}
	totalToHash := len(filesToHash)
	if totalToHash > 0 {
		fmt.Printf("Параллельное хеширование %d файлов (воркеров: %d)...\n", totalToHash, runtime.NumCPU())
		startHash := time.Now()

		jobs := make(chan *FileInfo, totalToHash)
		var wg sync.WaitGroup
		for w := 0; w < runtime.NumCPU(); w++ {
			wg.Add(1)
			go func() {
				defer wg.Done()
				for f := range jobs {
					hash, err := computeSHA256(f.Path)
					if err != nil {
						fmt.Fprintf(os.Stderr, "Ошибка чтения %s: %v\n", f.Path, err)
						continue
					}
					f.Hash = hash
				}
			}()
		}
		for _, f := range filesToHash {
			jobs <- f
		}
		close(jobs)
		wg.Wait()
		fmt.Printf("Хеширование завершено за %v\n", time.Since(startHash))
	}

	// ----- 4. Формирование дубликатов -----
	var csvRows [][]string
	bashLines := []string{"#!/bin/bash", "# Generated by find_dups", "set -e", ""}
	duplicatesCount := 0

	for size, files := range bySize {
		if len(files) < 2 {
			continue
		}
		hashGroups := make(map[string][]*FileInfo)
		for _, f := range files {
			if f.Hash != "" {
				hashGroups[f.Hash] = append(hashGroups[f.Hash], f)
			}
		}
		for hash, group := range hashGroups {
			if len(group) < 2 {
				continue
			}
			sort.Slice(group, func(i, j int) bool { return group[i].ID < group[j].ID })
			for _, f := range group {
				csvRows = append(csvRows, []string{
					fmt.Sprint(f.ID),
					f.Path,
					fmt.Sprint(size),
					hash,
					f.Birth.Format(time.RFC3339),
					f.ModTime.Format(time.RFC3339),
				})
			}
			for i, f := range group {
				if i == 0 {
					continue
				}
				duplicatesCount++
				bashLines = append(bashLines, fmt.Sprintf("rm -- %q", f.Path))
			}
		}
	}
	bashLines = append(bashLines, "", `echo "Deletion complete."`)

	// Запись CSV
	csvFile, _ := os.Create("duplicates_go.csv")
	defer csvFile.Close()
	csvWriter := csv.NewWriter(csvFile)
	defer csvWriter.Flush()
	csvWriter.Write([]string{"FileID", "Path", "Size", "Hash", "CreationTime", "ModificationTime"})
	csvWriter.WriteAll(csvRows)

	// Запись bash-скрипта
	shFile, _ := os.Create("duprm_go.sh")
	defer shFile.Close()
	for _, line := range bashLines {
		fmt.Fprintln(shFile, line)
	}
	shFile.Chmod(0755)

	// ----- 5. Сортированный CSV (все файлы) -----
	sorted := make([]FileInfo, len(allFiles))
	copy(sorted, allFiles)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Size > sorted[j].Size })
	sortFile, _ := os.Create("sort_dup_go.csv")
	defer sortFile.Close()
	sortWriter := csv.NewWriter(sortFile)
	defer sortWriter.Flush()
	sortWriter.Write([]string{"FileID", "Path", "Size", "Hash", "CreationTime", "ModificationTime"})
	for _, f := range sorted {
		sortWriter.Write([]string{
			fmt.Sprint(f.ID),
			f.Path,
			fmt.Sprint(f.Size),
			f.Hash,
			f.Birth.Format(time.RFC3339),
			f.ModTime.Format(time.RFC3339),
		})
	}

	// ----- 6. Статистика -----
	elapsed := time.Since(startTotal)
	fmt.Printf("\nПросмотрено файлов: %d\n", scanned)
	fmt.Printf("Найдено дубликатов (файлов для удаления): %d\n", duplicatesCount)
	fmt.Printf("Время работы:\n")
	fmt.Printf("  - %.3f секунд\n", elapsed.Seconds())
	fmt.Printf("  - %s\n", formatDuration(elapsed))
	fmt.Println("Отчёты: duplicates_go.csv, sort_dup_go.csv")
	fmt.Println("Скрипт удаления: duprm_go.sh")
}

func computeSHA256(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", h.Sum(nil)), nil
}

func formatDuration(d time.Duration) string {
	ms := d.Milliseconds()
	s := ms / 1000
	ms %= 1000
	m := s / 60
	s %= 60
	h := m / 60
	m %= 60
	return fmt.Sprintf("%02d:%02d:%02d.%03d", h, m, s, ms)
}

